name: Bug Report
description: Report a bug in Summa
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below.

  - type: input
    id: version
    attributes:
      label: Summa Version
      description: Which version of summa are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - summa
        - "@summa/core"
        - "@summa/drizzle-adapter"
        - "@summa/prisma-adapter"
        - "@summa/kysely-adapter"
        - "@summa/memory-adapter"
        - "@summa/cli"
        - "@summa/test-utils"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue
      render: typescript
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: adapter
    attributes:
      label: Database Adapter
      description: Which adapter are you using?
      options:
        - Drizzle
        - Prisma
        - Kysely
        - Memory
        - Other
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: "22.0.0"
    validations:
      required: false
